initial pass of resharing end to end
randa-mu/ssv-dkg pull request #9
Opened 2024-05-08 12:38 UTC by CluEleSsUK

- updated to go 1.22
- presently newly added nodes don't work (only resharing the same group)
- more tests needed

2024-05-24 09:17 UTC, AnomalRoil requested changes
First batch of comments

2024-05-24 09:17 UTC, AnomalRoil commented on cli/README.md
> +You will need to maintain this state file if you wish to reshare the key for this cluster in future, e.g. if operators become unresponsive and you wish to exclude them.
```suggestion
You will need to maintain this state file if you wish to reshare the key for this cluster in the future, e.g. if operators become unresponsive and you wish to exclude them. 
```

2024-05-24 09:17 UTC, AnomalRoil commented on cli/internal/cmd/reshare.go
> +}
I feel this could have deserved a bit more separation in order to have some tests

2024-05-24 09:17 UTC, AnomalRoil commented on cli/README.md
> +Note: you will have to maintain 50% + 1 of the same operators in the new cluster for this to succeed.
Not mega clear, might be rephrased maybe

2024-05-24 09:17 UTC, AnomalRoil commented on tools/stub/ssv-node-stub.go
these stub stuff might belong in `internal` rather, no?

2024-05-24 09:17 UTC, AnomalRoil commented on tools/stub/ssv-node-stub.go
> +		stop <- true
```suggestion
		close(stop)
```
so that it can be read as many time as you want in as many go routines as needed

2024-05-24 09:17 UTC, AnomalRoil commented on cli/internal/cmd/reshare.go
> +	operatorString := strings.Trim(string(stdin), "\n")
`Trim` is only removing leading and trailing newspaces, is that just what you want here?

2024-05-24 09:17 UTC, AnomalRoil commented on cli/internal/cmd/reshare.go
> +	return strings.Split(operatorString, " "), nil
so you're expecting operators to be provided in stdin as:
```
1,operator 2,opop 3,perper 4,ratorrator
```
am I reading that code correctly?

2024-05-24 09:17 UTC, AnomalRoil commented on cli/internal/cmd/sign.go
> +	Long:  "Signs ETH deposit data by forming a validator cluster that creates a distributed key. Operators can be passed via stdin.",
I'd specify the format we're expecting too.

2024-05-24 09:17 UTC, AnomalRoil commented on cli/internal/cmd/sign.go
> +		args = strings.Split(operatorString, " ")
I really think we should have some function somewhere doing that since we need it in more than one place and it's tricky if we change it in one place and not in the other later on.

2024-05-24 09:17 UTC, AnomalRoil commented on cli/reshare.go
> +	if err != nil {
```suggestion
	if err = verifyPublicPolynomialSameReshare(operatorResponses); err != nil {
```

2024-05-24 09:17 UTC, AnomalRoil commented on integration/dkg_error_processes.go
should probably be in `internal`

2024-05-24 09:17 UTC, AnomalRoil commented on integration/integration_test.go
should probably be in `internal` ?

2024-05-27 11:16 UTC, CluEleSsUK commented on tools/stub/ssv-node-stub.go
users may want to run the stub, so it's probably not `internal`

2024-05-27 11:21 UTC, CluEleSsUK commented on cli/internal/cmd/sign.go
> +	Long:  "Signs ETH deposit data by forming a validator cluster that creates a distributed key. Operators can be passed via stdin.",
Right now there isn't any validation on the format, though perhaps there ought to be

2024-05-27 11:37 UTC, CluEleSsUK commented on cli/internal/cmd/sign.go
> +		args = strings.Split(operatorString, " ")
have refactored the other function to do both

2024-05-28 07:12 UTC, CluEleSsUK commented on cli/internal/cmd/reshare.go
> +}
have pulled it into its own function

2024-05-28 09:22 UTC, merged